eureka:
  # eureka 客户端
  client:
    # 注册中心地址
    serviceUrl:
      defaultZone: http://@ms-server-url@:@ms-port-eureka@/eureka/

spring:
  application:
    # 表示到注册中心的应用名称
    name: erp-hr
  # 数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://@mysql-url@/erp_hr?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: @mysql-user@
    password: @mysql-password@
    max-idle: 10
    max-wait: 10000
    min-idle: 5

server:
  port: @ms-port-hr@