#
eureka:
  instance:
    hostname: 47.122.41.214
  client:
    # 表示是否注册到服务器。 因为它本身就是服务器，所以就无需把自己注册到服务器了。
    registerWithEureka: false
    #  表示是否获取服务器的注册信息，和上面同理，这里也设置为 false。
    fetchRegistry: false
    # 微服务公布地址
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: eureka-server
server:
  port: 8888