eureka:
  client:
    serviceUrl:
      defaultZone: http://@ms-server-url@:@ms-port-eureka@/eureka/

spring:
  application:
    name: erp-zuul

# 超时设置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000
ribbon:
  ConnectTimeout: 500
  ReadTimeout: 5000

zuul:
  ribbon.eager-load.enabled: true
  # 网关前缀
  prefix: /api
  # 路由
  routes:
    cloud-admin:
      path: /admin/**
      serviceId: ADMIN-MANAGEMENT

    cloud-commodity:
      path: /commodity/**
      serviceId: ERP-COMMODITY

    cloud-financial:
      path: /financial/**
      serviceId: ERP-FINANCIAL

    cloud-order:
      path: /order/**
      serviceId: ERP-ORDER

    cloud-production:
      path: /production/**
      serviceId: ERP-PRODUCTION

    cloud-warehouse:
      path: /warehouse/**
      serviceId: ERP-WAREHOUSE

    cloud-hr:
      path: /hr/**
      serviceId: ERP-HR
server:
  port: @ms-port-zuul@